const PAYMENT_METHODS_ARRAY = ['COD', 'VNPAY'];
const SIZES_ARRAY = ['S', 'M', 'L', 'XL'];
const COLORS_ARRAY = ['YELLOW', 'BROWN', 'GREEN', 'WHITE'];
const INVOICE_STATUS_ARRAY = [
   'PENDING',
   'CONFIRMED',
   'REQUEST_CANCEL',
   'CANCELLED',
   'ON_PREPARING',
   'ON_DELIVERING',
   'DELIVERED',
   'PAID',
];

const PAYMENT_METHODS = {
   COD: 'COD',
   VNPAY: 'VNPAY',
};

const INVOICE_STATUS = {
   PENDING: 'PENDING',
   CONFIRMED: 'CONFIRMED',
   REQUEST_CANCEL: 'REQUEST_CANCEL',
   CANCELLED: 'CANCELLED',
   ON_PREPARING: 'ON_PREPARING',
   ON_DELIVERING: 'ON_DELIVERING',
   DELIVERED: 'DELIVERED',
   PAID: 'PAID',
};

const VERIFY_TYPES = {
   EMAIL: 'EMAIL',
   RESET_PASSWORD: 'RESET_PASSWORD',
   CHANGE_EMAIL: 'CHANGE_EMAIL',
   CHANGE_PHONE_NUMBER: 'CHANGE_PHONE_NUMBER',
};

const NOTIFICATION_TYPES = {
   SYSTEM: 'SYSTEM',
   USER: 'USER',
   INVOICE: 'INVOICE',
   REVIEW: 'REVIEW',
   VOUCHER: 'VOUCHER',
   ACTIVITY: 'ACTIVITY',
   ALL: 'ALL',
};

const NOTIFICATION_TYPE_ARRAY = [
   'SYSTEM',
   'USER',
   'INVOICE',
   'REVIEW',
   'VOUCHER',
   'ACTIVITY',
   'ALL',
];

module.exports = {
   PAYMENT_METHODS_ARRAY,
   SIZES_ARRAY,
   COLORS_ARRAY,
   INVOICE_STATUS_ARRAY,
   INVOICE_STATUS,
   PAYMENT_METHODS,
   VERIFY_TYPES,
   NOTIFICATION_TYPES,
   NOTIFICATION_TYPE_ARRAY,
};
